### ISSUE TITLE
pkgdown website theme

### ISSUE THREAD

**Issue by CeresBarros** [bcgov/climr#198]
We're currently using the default theme for the `pkgdown` `climr` website, but can choose another from the ones shown here:
https://bootswatch.com/

Please note that for some , the navbars are too large and their size needs to be adjusted (see https://pkgdown.r-lib.org/articles/customise.html)
```
template:
  bootstrap: 5
  bootswatch: lux
  bslib:
    pkgdown-nav-height: 100px
```
